services:
  - type: web
    name: my-bot
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: python bot.py
